# Generated by Django 3.1.7 on 2021-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210327_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.ManyToManyField(to='webapp.Subject'),
        ),
        migrations.AddField(
            model_name='video',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='webinar',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
