# Generated by Django 3.1.7 on 2021-03-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210327_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='webinar',
            new_name='video',
        ),
    ]
