# Generated by Django 3.1.7 on 2021-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210327_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ManyToManyField(to='webapp.Course'),
        ),
    ]
